replicaCount: 1

image:
  repository: oroinc/runtime
  tag: "6.1-latest"
  pullPolicy: IfNotPresent

service:
  port: 9000

env:
  - name: ORO_ENV
    value: "prod"
  - name: ORO_LOG_PATH
    value: "php://stderr"
  - name: ORO_USER_RUNTIME
    value: "www-data"

podSecurityContext:
  runAsUser: 33
  runAsGroup: 33
  fsGroup: 33
