apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
  labels:
    app: search
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
        - name: elasticsearch
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-Ediscovery.type=single-node"
            - "-Expack.security.enabled=false"
            - "-Enetwork.host=0.0.0.0"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
