apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.auth.database | quote }}
            - name: MYSQL_USER
              value: {{ .Values.auth.username | quote }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.auth.password | quote }}
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.auth.rootPassword | quote }}
