apiVersion: v1
kind: Secret
metadata:
  name: {{ include "database.fullname" . }}-secret
  namespace: {{ .Values.global.namespace | default "orocommerce" }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.auth.password | b64enc }} 