apiVersion: v1
kind: Service
metadata:
  name: {{ include "database.fullname" . }}
  namespace: {{ .Values.global.namespace | default "orocommerce" }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "database.selectorLabels" . | nindent 4 }}
