apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-nginx
  namespace: {{ .Values.global.namespace | default "orocommerce" }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      # Docroot: assets publics de l'application OroCommerce
      root /var/www/oro/public;
      index index.php index.html;

      location /healthz {
        return 200 'ok';
        add_header Content-Type text/plain;
      }

      # Délègue l'exécution PHP à PHP-FPM (backend)
      location /index.php {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_pass {{ include "backend.serviceName" . }}:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTPS off;
      }

      location ~ \.php$ {
        return 404;
      }

      location / {
        try_files $uri /index.php$is_args$args;
      }
    }
