apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend.fullname" . }}
  namespace: {{ .Values.global.namespace | default "orocommerce" }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "frontend.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
      - name: wait-for-backend
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - |
          until nc -z {{ include "backend.serviceName" . }} 9000; do
            echo "Waiting for backend service..."
            sleep 5
          done
          echo "Backend is ready!"
      containers:
      - name: nginx
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["nginx", "-g", "daemon off;"]
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: orocommerce-app
          mountPath: /var/www/oro
        - name: uploads
          mountPath: /var/www/oro/public/uploads
        env:
        - name: BACKEND_HOST
          value: {{ include "backend.serviceName" . }}
        - name: BACKEND_PORT
          value: "9000"
      volumes:
      - name: orocommerce-app
        persistentVolumeClaim:
          claimName: orocommerce-app-pvc
      - name: uploads
        persistentVolumeClaim:
          claimName: orocommerce-uploads-pvc 