image:
  repository: oroinc/runtime
  tag: 6.1-latest
  pullPolicy: IfNotPresent

initContainer:
  image:
    repository: oroinc/orocommerce-application
    tag: 6.1.0
    
  env:
    APP_ENV: "prod"

service:
  type: ClusterIP
  port: 80

web:
  replicas: 1
  volumes:
    oroApp:
      claimName: "oro-app-orocommerce"
    cache:
      claimName: "cache-orocommerce"
    maintenance:
      claimName: "maintenance-orocommerce"
    publicStorage:
      claimName: "public-storage-orocommerce"
    privateStorage:
      claimName: "private-storage-orocommerce"