apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}
  labels:
    app: {{ .Values.metadata.labels.app }}
    tier: {{ .Values.metadata.labels.tier }}
    role: {{ .Values.metadata.labels.role }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
      matchLabels:
        app: {{ .Values.metadata.labels.app }}
        tier: {{ .Values.metadata.labels.tier }}
        role: {{ .Values.metadata.labels.role }}
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.labels.app }}
        tier: {{ .Values.metadata.labels.tier }}
        role: {{ .Values.metadata.labels.role }}
    spec:
      containers:
        - name: {{ .Values.metadata.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          resources:
            requests:
              cpu: 100m
              memory: 100Mi