apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "web.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "web.name" . }}
    {{- include "web.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "web.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "web.name" . }}
    {{- include "web.labels" . | nindent 4 }}
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "web.fullname" . }}-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "web.name" . }}
    {{- include "web.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "web.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "web.fullname" . }}
  namespace: {{ .Release.Namespace }} 