# Configuration globale OroCommerce - Projet EII 5
global:
  domain: "orocommerce.local"
  namespace: "orocommerce"
  storageClass: ""
  elasticsearch:
    scheme: "http"
    port: 9200
  
  # Configuration base de données partagée
  database:
    name: "orocommerce"
    username: "orocommerce"
    password: "OroCommerce123!"
  
  # Images officielles OroCommerce
  images:
    orocommerce: "oroinc/orocommerce-application:6.1.0"
    runtime: "oroinc/runtime:6.1-latest"
    database: "postgres:15-alpine"

# Frontend minimal
frontend:
  enabled: true
  replicaCount: 1
  image:
    repository: nginx
    tag: "1.25-alpine"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80

# Backend: PHP-FPM (Deployment + HPA)
backend:
  enabled: true
  replicaCount: 1
  image:
    repository: oroinc/runtime
    tag: "6.1-latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9000
  # HPA Configuration
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

# Database: PostgreSQL (StatefulSet + PVC)
database:
  enabled: true
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3306
  auth:
    database: "orocommerce"
    username: "orocommerce"
    password: "OroCommerce123!"
    rootPassword: "OroCommerceRoot123!"

# Enable Redis and Elasticsearch subcharts
cache:
  enabled: true

search:
  enabled: true

# Monitoring: Prometheus + Grafana
monitoring:
  enabled: false

# Image configuration principale
image:
  repository: oroinc/orocommerce-application
  tag: "6.1.0"
  pullPolicy: IfNotPresent

# Service principal (pour les tests)
service:
  type: ClusterIP
  port: 80

# ServiceAccount configuration
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

# Ingress configuration
ingress:
  enabled: false

# Replica count
replicaCount: 1

# Image pull secrets
imagePullSecrets: []

# Pod annotations and labels
podAnnotations: {}
podLabels: {}

# Security contexts
podSecurityContext: {}
securityContext: {}

# Probes
livenessProbe: {}
readinessProbe: {}

# Resources
resources: {}

# Volume mounts and volumes
volumeMounts: []
volumes: []

# Node selection and affinity
nodeSelector: {}
affinity: {}
tolerations: []

# Autoscaling configuration (HPA)
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Configuration commune
secrets:
  database:
    password: "OroCommerce123!"
  grafana:
    adminPassword: "admin123"

# Volumes partagés
persistence:
  oroapp:
    size: 5Gi
    accessMode: ReadWriteMany
  uploads:
    size: 2Gi
    accessMode: ReadWriteMany
