# Configuration globale OroCommerce - Projet EII 5
global:
  domain: "orocommerce.local"
  namespace: "orocommerce"
  storageClass: ""
  
  # Configuration base de données partagée
  database:
    name: "orocommerce"
    username: "orocommerce"
    password: "OroCommerce123!"
  
  # Images officielles OroCommerce
  images:
    orocommerce: "oroinc/orocommerce-application:6.1.0"
    runtime: "oroinc/runtime:6.1-latest"
    database: "postgres:15-alpine"

# Frontend: Nginx (Deployment + Service)
frontend:
  enabled: true
  replicaCount: 2
  image:
    repository: oroinc/runtime
    tag: "6.1-latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: "nginx"
    host: "orocommerce.local"
    tls:
      enabled: true
      secretName: "orocommerce-tls"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# Backend: PHP-FPM (Deployment + HPA)
backend:
  enabled: true
  replicaCount: 2
  image:
    repository: oroinc/orocommerce-application
    tag: "6.1.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9000
  # HPA Configuration
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

# Database: PostgreSQL (StatefulSet + PVC)
database:
  enabled: true
  image:
    repository: postgres
    tag: "15-alpine"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5432
  persistence:
    enabled: true
    size: 10Gi
    accessMode: ReadWriteOnce
  auth:
    database: "orocommerce"
    username: "orocommerce"
    password: "OroCommerce123!"
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

# Monitoring: Prometheus + Grafana
monitoring:
  enabled: true
  prometheus:
    enabled: true
    image:
      repository: prom/prometheus
      tag: "v2.47.0"
    service:
      type: ClusterIP
      port: 9090
    persistence:
      enabled: true
      size: 5Gi
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
  grafana:
    enabled: true
    image:
      repository: grafana/grafana
      tag: "10.1.0"
    service:
      type: ClusterIP
      port: 3000
    auth:
      adminUser: "admin"
      adminPassword: "admin123"
    persistence:
      enabled: true
      size: 1Gi
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi

# Image configuration principale
image:
  repository: oroinc/orocommerce-application
  tag: "6.1.0"
  pullPolicy: IfNotPresent

# Service principal (pour les tests)
service:
  type: ClusterIP
  port: 80

# ServiceAccount configuration
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: orocommerce.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: orocommerce-tls
      hosts:
        - orocommerce.local

# Replica count
replicaCount: 1

# Image pull secrets
imagePullSecrets: []

# Pod annotations and labels
podAnnotations: {}
podLabels: {}

# Security contexts
podSecurityContext: {}
securityContext: {}

# Probes
livenessProbe: {}
readinessProbe: {}

# Resources
resources: {}

# Volume mounts and volumes
volumeMounts: []
volumes: []

# Node selection and affinity
nodeSelector: {}
affinity: {}
tolerations: []

# Autoscaling configuration (HPA)
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Configuration commune
secrets:
  database:
    password: "OroCommerce123!"
  grafana:
    adminPassword: "admin123"

# Volumes partagés
persistence:
  oroapp:
    size: 5Gi
    accessMode: ReadWriteMany
  uploads:
    size: 2Gi
    accessMode: ReadWriteMany
