apiVersion: v1
kind: Service
metadata:
  name: backend
  labels: { app: backend }
spec:
  type: ClusterIP
  selector: { app: backend }
  ports:
    - name: php-fpm
      port: {{ .Values.service.port }}     # 9000
      targetPort: php-fpm
      protocol: TCP
